let zh = {
    'index_sentence1': '「不斷吸取新的觀點和方法，探索周圍環境中人們的各個方面。」',
    'index_sentence2': '擁有兩年的 UI/UX 設計經驗，目前正在尋找 UX 設計師的相關工作。是個網路成癮者，但也喜愛在大自然裡走動',
    'index_sentence3': '可以在<a href="./download/edie_lin_resume2018_zh.pdf" class="link-blue">這邊下載我的簡歷</a> 💡',
    'about_me': '哈囉你好，我是林佳瑩，你可以叫我 Edie (音同ED)，擁有兩年的 UI/UX 設計經驗，可幫助您提升用戶體驗及轉換率。而與其說 UX 是一種技能，我更傾向它是一種思考模式，透過不斷思索、模擬與測試驗證，一步一步建構出符合使用者需求、商業目標、技術能力的優良產品。了解前端開發，具備能與工程師溝通的共同語言。<br />歡迎<a href="./download/edie_lin_resume2018_zh.pdf" class="link-blue">下載我的簡歷</a> 💡',
    'experience_6pm': 'UI/UX Designer | 六點互動科技有限公司',
    'experience_6pm_list': [
        '為公司產品重新設計的主要設計師',
        '找出用戶的需求和要求，進而改善用戶體驗及介面',
        '確保產品功能和使用流程符合使用者需求，幫助他們做出正確的決策',
        '與工程師密切合作，設計和開發出易用、合乎邏輯並擁有一致性的使用者介面',
        '積極地去做全面性的了解並用心體會使用者感受',
        '提供 UI/UX 設計給 3 個<a href="blossom-edugroup-app.html" class="link-blue" target="_blank">應用程式</a>',
        '設計並建造出 3 個<a href="web-design-collection.html" class="link-blue" target="_blank">網站</a>'
    ],
    'experience_iii': 'Web/App前端設計開發工程師養成班 | 資訊工業策進會',
    'experience_iii_list': [
        '從頭發想並獨立架設出 1 個<a href="http://140.115.236.72/demo-personal/AD103/web/C1600440/_myWeb2/" class="link-blue" target="_blank">靜態網站</a><br />(視覺設計 1st、最佳 RWD 2nd、最佳網站 2nd)',
        '1 個團隊<a href="http://140.115.236.72/demo-projects/AD103/AD103G1/g1_hoyo/index.php" class="link-blue" target="_blank">合作網站</a>，主要負責首頁及會員專區',
        '1 個應用程式介面設計',
    ],
    'education': '資訊模擬與設計學系 | 實踐大學',
    'skill_uiux': '製作 User story, flow charts, wireframes, sitemaps, prototyping',
    'skill_f2e': '前端開發',
    'f2e_description': '具前端開發的堅強基礎',
    'skill_collaboration': '共同協作',
    'collaboration_description': '與團隊溝通協作，邁向共同目標',
    'interest_list': [
        '對變化快速的新資訊保持靈敏度 一 網路成癮者',
        '在大自然裡走動，綠色對眼睛有幫助',
        '看看展覽、逛逛市集，美好設計帶來美好生活',
        '觀察別人做料理，是魔法',
        '空氣鳳梨，獨立自主新植物'
    ],
    'app_introduce': '一款專為 Blossom Edugroup 花萌教育幼稚園所製作的App。上學時，老師們用它來記錄孩子到校及健康狀況；放學時，確保孩子是經由認可的親友接送離開。使用裝置固定為 Android Tablets，必須連結藍芽體溫計記錄體溫。',
    'app_5w1h': '一開始，園方提供給我們一份需求書，根據需求書我整理出 5W1H：',
    'app_who': '誰是這個 App 的使用者？ — 花萌教育的老師們',
    'app_what_how': '他們要用這個 App 來完成什麼事？要如何執行這些任務？<br />— 紀錄孩子們的到校及健康狀況；使用藍芽溫度計測量孩子們的體溫，用視覺判斷孩子是否安全無虞',
    'app_why': '為什麼他們需要完成這些任務？真正想要完成什麼？<br />— 確認每個在幼稚園的孩子都是健康及安全的、打造優良口碑，如有狀況發生，釐清責任歸屬',
    'app_where_when': '在何時何地使用這個 App？趕時間嗎？使用頻率？<br />— 校門口教室內；每天的上學及放學時段',
    'app_5w1h_goodgood': '5W1H 可幫助我們投入於使用情境，在設計過程中創造出良好的用戶體驗',
    'flow_chart': '在理解使用需求後，我便開始製作流程圖，用來模擬使用者的操作邏輯，也是之後畫 wireframe 的重要依據，包含頁面與頁面之間的關係，同時也再確認應有的功能。',
    'wireframe': '先以素描快速畫出黑白單色框線圖，並一邊與我的夥伴討論加以確認 UI 位置及設計想法。',
    'prototyping': '透過可操作的原型設計，測試使用者在操作過程中是否會感到任何不順暢或遲疑的地方。<br />你可以在<a href="https://xd.adobe.com/view/56937f5d-6a2f-4a7e-4e37-a872237db707-20a2/" class="link-blue" target="_blank">這裡</a>一起操作原型並觀看完整畫面',
    'app_design_high_light': '由於是專為花萌教育所做的 App，在使用者以及使用裝置方面上單純許多，但我們所擁有的製作時間並不算充裕（設計流程大約一個禮拜），而以 ionic 建構此 App 也是一項挑戰。<br />在畫面設計上我遵從 Material design guideline，並跟隨使用流程表直觀地指引使用者操作，功能雖然簡易但絕不馬虎帶過。最後我也加入 ionic coding 的行列，確保畫面呈現能與設計圖稿保持一致。',
    'ljc_intro': '一個新加坡物流公司的形象網站。初期設計困難點在於對方所提供的資料雜亂無章，而人類對於資訊的理解及記憶從分類開始，我從中找出有意義並相關聯的組合，點出標題，再賦予CTA，使畫面呈現能具有層次感。<br />你可以在<a href="https://www.ljcexpress.com.sg/" class="link-blue" target="_blank">這裡</a>找到它',
    'mockup': '一般我會先製作平面視覺圖供客戶參閱，確認無誤後才會進入 HTML 切版的部分。在繪製 Mockup 時，同時也在建立視覺模組、訂下一致性的設計規範。前置作業定義出標準，團隊溝通及共識上便能有所依據，對後續的工作十分有利。',
    'deploy': '網站也是由我部屬配置，在設計時便已先評估可行性，避免出現不切實際的虛華畫面。越有充分的規劃，越能降低所花費的時間及困難度。最後在部屬 HTML 及 CSS 便是相對輕鬆且快速。',
    'web_6c_desc': '形象網站。連結企業和物流公司之間的系統平台',
    'web_6p_desc': '形象網站。為物流公司的打造的管理系統',
    'web_letter_desc': '資策會個人作品',
    'web_hoyo_desc': '資策會專題作品'
}